spring:
  application:
    name: demoLog4j
  datasource:
    url: jdbc:mariadb://localhost:3307/demolog4j
    username: root
    password: giang412345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

server:
  servlet:
    session:
      timeout: 30m
